[versions]
activityKtx = "1.10.1"
agp = "8.9.3"
androidxJunit = "1.2.1"
appcompatVersion = "1.7.1"
composeBom = "2025.06.00"
constraintlayoutVersion = "2.2.1"
coreKtxVersion = "1.16.0"
espressoCoreVersion = "3.6.1"
facebookAndroidSdk = "18.0.3"
facebookAndroidSdkVersion = "18.0.3"
facebookFacebookAndroidSdk = "18.0.3"
facebookLogin = "18.0.3"
firebaseBomVersion = "33.14.0"
firebaseUiAuthVersion = "9.0.0"
googleFirebaseBom = "33.14.0"
googleFirebaseBomVersion = "33.15.0"
kotlin = "2.1.20"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
kotlinCompilerExtensionVersion = "2.1.20"
androidx-compose-ui = "1.8.2" # Or your desired version
okhttp = "4.12.0"
firebase-perf = "21.0.5"
androidx-core = "1.9.0"
compose-ui = "1.8.2" # Or your desired Compose UI version


# ... 다른 버전들 ...
firebaseBom = "34.0.0"  # Firebase BOM 최신 버전
firebaseUiAuth = "9.0.0"  # Firebase UI Auth 최신 버전

# Jetpack Compose 관련 버전 (예시, 이미 있다면 그대로 사용)

# ... 기타 필요한 버전들 ...
# Android Gradle Plugin (AGP) 버전

googleGmsServices = "4.4.2" # Google Services 플러그인 버전을 확인하세요.
materialVersion = "1.12.0"

# ... 기타 필요한 버전들 (예: firebaseBom, firebaseUiAuth 등)

androidxActivityKtx = "1.10.1"
<<<<<<< HEAD
firebaseAuthKtx = "23.2.1" # Or your desired version
androidGradlePlugin = "8.9.1"


=======
firebaseAuthKtx = "23.2.1"
firebaseCommonKtx = "21.0.0"
firebaseFirestoreKtx = "25.1.4" # Or your desired version
>>>>>>> e433a96 (메이져 브런치 인증2025.06.15)


[libraries]


androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
# Ensure these lines (or similar) exist and use the correct version reference

#androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeUi" } # If you use Material 1



firebase-bom-v33140 = { module = "com.google.firebase:firebase-bom", version.ref = "googleFirebaseBomVersion" }
okhttp-lib = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
firebase-perf-lib = { module = "com.google.firebase:firebase-perf", version.ref = "firebase-perf" }

androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivityKtx" }


androidx-appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-compose-bom-v20240100 = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidx-compose-ui" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
facebook-android-sdk = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebookAndroidSdk" }
facebook-android-sdk-v1600 = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebookFacebookAndroidSdk" }
facebook-android-sdk-v8x = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebookAndroidSdkVersion" }
facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebookLogin" }


# Firebase BOM을 통해 모든 Firebase 라이브러리 버전 자동 관리
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }

# Firebase 라이브러리 (BOM을 통해 버전 자동 적용)
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }

# Firebase UI Auth (BOM과 별도로 관리)
firebase-ui-auth = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebaseUiAuth" }



junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }





# Jetpack Compose (예시, 이미 있다면 그대로 사용)
#androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
ui = { module = "androidx.compose.ui:ui" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx", version.ref = "firebaseCommonKtx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
# ... 기타 Compose 라이브러리들 ..


# firebase-ui-auth = { group = "com.firebaseui", name = "firebase-ui-auth", version.ref = "firebaseUiAuth" } # 필요하다면 추가




[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsServices" }
androidx-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinCompilerExtensionVersion" }
android-library = { id = "com.android.library", version.ref = "agp" }


